# The config recipe.
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: atguigu_ecs

language: zh

pipeline:
#- name: CompactLLMCommandGenerator
- name: SearchReadyLLMCommandGenerator
  llm:
    model_group: qwen
#    model_group: qwen3_8b
  flow_retrieval:
    active: false # 禁用流程检索，默认使用的openai的Embedding模型 text-embedding-3-large，会要求 openai 的 key

# Configuration for Rasa Core.
policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
  llm:
    model_group: qwen
  embeddings:
    model_group: embedding_models
  vector_store:
    type: "addons.information_retrieval.GraphRAG"

#- name: IntentlessPolicy  # 默认会调用 openai的 gpt-4o,，会要求 openai 的 key
